name: Compiler Compatibility CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu2204:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { tag: "clang-12", name: "Clang 12", cxx: "/usr/bin/clang++-12", cc: "/usr/bin/clang-12" }
          - { tag: "clang-13", name: "Clang 13", cxx: "/usr/bin/clang++-13", cc: "/usr/bin/clang-13" }
          - { tag: "clang-14", name: "Clang 14", cxx: "/usr/bin/clang++-14", cc: "/usr/bin/clang-14" }
          - { tag: "g++-9", name: "G++ 9", cxx: "/usr/bin/g++-9", cc: "/usr/bin/gcc-9" }
          - { tag: "g++-10", name: "G++10", cxx: "/usr/bin/g++-10", cc: "/usr/bin/gcc-10" }
          - { tag: "g++-11", name: "G++11", cxx: "/usr/bin/g++-11", cc: "/usr/bin/gcc-11" }
    name: Compiler ${{ matrix.compiler.name }}
    env:
      CXX: ${{ matrix.compiler.cxx }}
      CC: ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/gtest
      - name: Configure
        run: cmake . -DASYNCPP_BUILD_TEST=ON -G 'Unix Makefiles'
      - name: Build
        run: cmake --build .
      - name: Test
        run: ./asyncpp-test

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: ubuntu2204
          label: ${{ matrix.compiler.name }}
  
  ubuntu2004:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { tag: "clang-12", name: "Clang 12", cxx: "/usr/bin/clang++-12", cc: "/usr/bin/clang-12" }
          - { tag: "clang-11", name: "Clang 11", cxx: "/usr/bin/clang++-11", cc: "/usr/bin/clang-11" }
          - { tag: "clang-10", name: "Clang 10", cxx: "/usr/bin/clang++-10", cc: "/usr/bin/clang-10" }
          - { tag: "g++-9", name: "G++ 9", cxx: "/usr/bin/g++-9", cc: "/usr/bin/gcc-9" }
          - { tag: "g++-10", name: "G++10", cxx: "/usr/bin/g++-10", cc: "/usr/bin/gcc-10" }
    name: Compiler ${{ matrix.compiler.name }}
    env:
      CXX: ${{ matrix.compiler.cxx }}
      CC: ${{ matrix.compiler.cc }}
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/gtest
      - name: Configure
        run: cmake . -DASYNCPP_BUILD_TEST=ON -G 'Unix Makefiles'
      - name: Build
        run: cmake --build .
      - name: Test
        run: ./asyncpp-test

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: ubuntu2004
          label: ${{ matrix.compiler.name }}
